version: "3.9"
services:
  teleophtalmo:
    ipc: host
    build:
      context: ../
      dockerfile: $PWD/docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - $PWD/models:/app/models
      - /home/jupyter/Data:/app/datasets/ORIGA
      - /home/thomas/TeleOphtalmo/module/output_MaskRcnn_ORIGA/:/app/datasets/ORIGA_cropped
      - /home/jupyter/Second_branch/data_train_mrcnn/:/app/datasets/IDRID
      - /home/jupyter/Third_branch/mask_for_maskrcnn/:/app/datasets/MAGRABIA
      - /home/jupyter/All_final_models:/app/models/final
      - /home/thomas/TeleOphtalmo/module/output:/app/datasets/logistic_regression
      - /home/thomas/TeleOphtalmo/module/config.py:/app/config.py
